theme: fluency
languageCode: zh-tw
title: " 逢甲大學遊戲開發社"
pygmentsUseClasses: true # enable theme-defined highlight style
# pygmentsCodefences: true
baseURL: https://fcugdc.github.io/blog/
menu:
  main:
    - identifier: tutorial
      name: 教學講義
      url: tutorial/
      weight: -35
    - identifier: posts
      name: 社團公告
      url: posts/
      weight: -40
    - identifier: tags
      name: 分類標籤
      url: tags/
      weight: -30
    - identifier: discord
      name: Discord
      url: https://discord.gg/ZkDCb8fmr3
      weight: -20
    - identifier: about
      name: 關於我們
      url: about/
      weight: -10
  footer:
    - identifier: github
      url: "https://github.com/FCUGDC"
      name: Github
    - identifier: discord
      url: "https://discord.gg/ZkDCb8fmr3"
      name: Discord
params:
  pageSize:
    index: 5
    list: 10
    terms: 60
    archives: 20
  copyright: "© 2021 逢甲大學遊戲開發社"
  mainSections:
    - posts
    - pics
  disableComment: true
  disableCommentByType:
    - page
  thirdPartyComment: |
    this is your comment
  publishDir: docs
  enableRobotsTXT: true
  hasCJKLanguage: true
  timeZone: Asia/Taipei
  summaryLength: 35 